[package]
name = "ece459-e1"
version = "0.1.0"
authors = ["Vinai Birbal <vinai.birbal@uwaterloo.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
